package io.turbine.core.verticles;

import io.reactivex.Single;
import io.turbine.core.jdbc.queries.QueryBuilder;
import io.turbine.core.jdbc.queries.QueryBuilderImpl;
import io.turbine.core.jdbc.results.Results;
import io.turbine.core.verticles.behaviors.DataVerticle;
import io.vertx.core.Context;
import io.vertx.core.Vertx;
import io.vertx.ext.sql.SQLOptions;
import io.vertx.reactivex.ext.jdbc.JDBCClient;
import io.vertx.reactivex.ext.sql.SQLConnection;

import static io.vertx.reactivex.ext.jdbc.JDBCClient.createShared;

public abstract class BaseDataVerticle extends BaseVerticle implements DataVerticle {

    private JDBCClient jdbc;
    private final QueryBuilder queryBuilder = new QueryBuilderImpl();

    @Override
    public final QueryBuilder query() {
        return queryBuilder;
    }

    @Override
    public void init(Vertx vertx, Context context) {
        super.init(vertx, context);

        jdbc = createShared(this.vertx, jdbcConfiguration());
        connect()
            .doOnSuccess(connection -> {
                connection.close();
                logger.info("Asynchronous JDBC client ready, connection to the DBMS tested OK");
            })
            .subscribe();
    }

    @Override
    public final Single<SQLConnection> connect() {
        return jdbc.rxGetConnection()
                .map(c -> c.setOptions(sqlOptions()));
    }

    @Override
    public SQLOptions sqlOptions() {
        return new SQLOptions().setAutoGeneratedKeys(true);
    }

    public Single<Results> single(String sql, Object... params) {
        return connect().flatMap(queryBuilder.single(sql, params));
    }

    public Single<Results> select(String sql, Object... params) {
        return connect().flatMap(queryBuilder.select(sql, params));
    }

    public Single<Integer> update(String sql, Object... params) {
        return connect().flatMap(queryBuilder.update(sql, params));
    }
}
